### ISSUE TITLE
Minor Issue With Fixes - Pixelmon Crashes when clicking on JEI "Legendary Bird Shrines and Orbs"

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [P3rf3ctXZer0/Zer0Necrosis-Project-Workbench#5]
At this time do no simply click the orb just make it. in JEI is crashes. Their solution was to downgrade forge. This is simply impossible since many mods in this pack benefit from forge 805 and up.

https://pixelmonmod.com/wiki/index.php?title=Orb_of_Frozen_Souls

**Comment by P3rf3ctXZer0** [comment]
Upon further investigation in Quark may be the cause. Something with the lighting engine. @Vazkii

**Comment by P3rf3ctXZer0** [comment]
https://gist.github.com/P3rf3ctXZer0/fd76ccd011f0bbbd92979416e3c922d7
[crash-2019-01-19_13.28.38-client.txt](https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/files/2775905/crash-2019-01-19_13.28.38-client.txt)
[latest.log](https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/files/2775906/latest.log)

**Comment by P3rf3ctXZer0** [comment]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at net.minecraftforge.client.model.pipeline.LightUtil$ItemConsumer.put(LightUtil.java:327) ~[LightUtil$ItemConsumer.class:?]
	at net.minecraftforge.client.model.pipeline.LightUtil.putBakedQuad(LightUtil.java:117) ~[LightUtil.class:?]
	at net.minecraft.client.renderer.block.model.BakedQuad.pipe(BakedQuad.java:66) ~[bvp.class:?]
	at net.minecraftforge.client.model.pipeline.LightUtil.renderQuadColorSlow(LightUtil.java:286) ~[LightUtil.class:?]
	at net.minecraftforge.client.model.pipeline.LightUtil.renderQuadColor(LightUtil.java:298) ~[LightUtil.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191970_a(RenderItem.java:226) ~[bzw.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawSegment(ForgeHooksClient.java:751) ~[ForgeHooksClient.class:?]
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:713) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347) ~[bzw.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:27) ~[ItemStackRenderer.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:20) ~[ItemStackRenderer.class:?]
	at mezz.jei.gui.ingredients.GuiIngredient.draw(GuiIngredient.java:168) ~[GuiIngredient.class:?]
	at mezz.jei.gui.ingredients.GuiIngredientGroup.draw(GuiIngredientGroup.java:156) ~[GuiIngredientGroup.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:167) ~[RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:218) ~[RecipesGui.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) ~[buq.class:?]
	... 17 more
[13:12:46] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

**Comment by P3rf3ctXZer0** [comment]
https://github.com/mezz/JustEnoughItems/issues/1470

**Comment by P3rf3ctXZer0** [comment]
Temporary - Hiding JEI Recipe

**Comment by P3rf3ctXZer0** [comment]
Removing conventional legendary bird spawning! Legendary birds will now randomly spawn at night!

**Comment by P3rf3ctXZer0** [comment]
Also please ignore bird shrines all together
